name: Test 1 - Fetch Planets

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm install -g jest # Instala Jest globalmente
      - run: jest -t "Should fetch planets" # Executa Jest globalmente

